#!/bin/bash

# set -e command is imported by under the each source.
for f in $(find ./src/ -maxdepth 1 -name "*.sh"); do source "${f}"; done

while (( $# != 0 )); do
  case $1 in
    -h|--help)
      usage
      ;;
    -v|--version)
      version
      ;;
    -d|--debug)
      logging_msg "DEBUG" "running on Debug mode."
      set -x
      shift
      ;;
    --logging_test)
      logging_test
      ;;
    -*|--*)
      echo "$0: $1: invalid option"
      echo "$0: usage: $0 [-h|--help] [-v|--version] [-d|--debug]"
      exit 1
      ;;
    *)
      echo "$0: $1: invalid argument"
      echo "$0: usage: $0 [-h|--help] [-v|--version] [-d|--debug]"
      exit 1
      ;;
  esac
done

#logging_start ./logs

#subprocess_logging ./subprocess "This is useless arguments"
#echo $?

set +e
set -o pipefail

cat 1234.qwe 2>&1 | while IFS= read -r line; do
  echo $line
done
echo "hahha:$?"

